[package]
name = "flowge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm17-0-force-dynamic"] }
